update github ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,8 +1,14 @@
-on: push
+name: Test CI
+
+on: [push, pull_request]
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
   cancel-in-progress: true
+
+env:
+  qemu-version: 10.0.2
+  rust-toolchain: nightly-2025-05-20
 
 jobs:
   build:
@@ -36,3 +42,47 @@ jobs:
 
       - name: Build
         run: make ARCH=${{ matrix.arch }} build
+
+  test:
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-latest]
+        arch: [riscv64]
+    env:
+      RUSTUP_TOOLCHAIN: nightly-2025-05-20
+    steps:
+    - uses: actions/checkout@v4
+    - uses: dtolnay/rust-toolchain@stable
+      with:
+        toolchain: ${{ env.rust-toolchain }}
+        components: rust-src, llvm-tools
+        targets: riscv64gc-unknown-none-elf
+    - uses: Swatinem/rust-cache@v2
+      with:
+        shared-key: cargo-bin-cache-${{ env.rust-toolchain }}
+        cache-targets: false
+    - uses: arceos-org/setup-qemu@v1
+      with:
+        version: ${{ env.qemu-version }}
+        arch_list: riscv64
+    - uses: arceos-org/setup-musl@v1
+      with:
+        arch: ${{ matrix.arch }}
+    - name: Run alpine linux fs image
+      timeout-minutes: 5
+      run: |
+        LOG=qemu-${{ matrix.arch }}.log
+        make ARCH=${{ matrix.arch }} build
+        make ARCH=${{ matrix.arch }} img
+        make ARCH=${{ matrix.arch }} run > $LOG 2>&1
+        sleep 25
+        pkill qemu || true
+        if grep -qE "sh-.*#|/#" $LOG; then
+          echo "✅ Kernel booted to BusyBox shell"
+        else
+          echo "❌ Boot failed, QEMU log:"
+           cat $LOG
+           exit 1
+        fi
